### ISSUE TITLE
React Prérequis JavaScript - QCM5 - question 4

### ISSUE THREAD

**Issue by thpGitHub** [MikeCodeur/react-prerequis-javascript#3]
La bonne syntaxe d'une ternaire est :
pageCode == 404 : 'page not found' ? 'page found'

Pour moi la bonne réponse est plutôt : 
pageCode == 404 ? 'page not found' : 'page found'

**Comment by nadlgit** [comment]
Idem

**Comment by MikeCodeur** [comment]
yes, fix
