### ISSUE TITLE
Prérequis JS ES6 exercice 1 périmètre

### ISSUE THREAD

**Issue by AlexSnooTwo** [MikeCodeur/react-prerequis-javascript#5]
Je pense que certains l'auront remarqué, mais dans le fichier roomHelper Mowglie le chien nous aide à définir la fonction périmètre.
Hors la formule n'est pas bonne, le périmètre n'est pas :
 longueur x largeur x 2
 mais plutôt
 (longueur + largeur) x 2.

**Comment by MikeCodeur** [comment]
yes, fix
