### ISSUE TITLE
React Prérequis JavaScript - QCM6 - question 4

### ISSUE THREAD

**Issue by nadlgit** [MikeCodeur/react-prerequis-javascript#6]
De ma compréhension de la doc, la réponse à la question 4 du QCM6 "array.map() retourne ..." devrait être "Un array"

**Comment by washtakzo** [comment]
![image](https://user-images.githubusercontent.com/101528828/172824024-7690f555-0f27-401c-9743-80012a1caef1.png)
Oui il y a une erreur

**Comment by MikeCodeur** [comment]
yes, fix
