### ISSUE TITLE
Erreur dans module 'React Prérequis JavaScript' du QCM 5 - Question 4/4

### ISSUE THREAD

**Issue by electroheadfx** [MikeCodeur/react-prerequis-javascript#8]
![Capture d’écran 2022-03-14 à 14 18 50](https://user-images.githubusercontent.com/1211149/158180576-8169ff05-f372-4577-94b7-d3630fbcef9c.png)

La bonne réponse c'est pas le N°2, c'est bien le N°1

Laurent@efx

**Comment by MikeCodeur** [comment]
yes, fix
